### ISSUE TITLE
Brake Bias .5 Increment

### ISSUE THREAD

**Issue by BadBoyClub** [SIMRacingApps/SIMRacingApps#103]
On the brake bias adjustment in the Brake Pressure widget, 'BarGauge-BrakePressure' - it would be great to have .5 increments displayed

Currently it will only display 47 or 48 but not 47.5

**Comment by jfgilliam** [comment]
OK, I'll put this in the next BETA for 1.4

**Comment by jfgilliam** [comment]
Just posted the BETA release for this at https://github.com/SIMRacingApps/SIMRacingApps/releases/tag/Version_1.4_Build_BETA-2017.06.23
