### ISSUE TITLE
PitCommands: Changes tires when you drop onto pit road.

### ISSUE THREAD

**Issue by jfgilliam** [SIMRacingApps/SIMRacingApps#108]
After a reset or if you've been in the garage, when you drop onto pit road, it will change your tires. I think this may also be related to the issue that does the same thing when swapping drivers.

**Comment by Rambler4266** [comment]
is there a fix for this?

**Comment by jfgilliam** [comment]
I'm working on it now. Turns out I had to rewrite a lot of my logic and it's taking a while.

**Comment by Rambler4266** [comment]
Thank you. LOVE the app!!!!!!!!!!!!!!!!!!!!!!!!
