### ISSUE TITLE
Widgets without title bar?

### ISSUE THREAD

**Issue by SeanP171** [SIMRacingApps/SIMRacingApps#109]
Is there a way to open widgets without the title bar, I want to just see the widget, not everything else.

**Comment by jfgilliam** [comment]
You can, but you have to use the Electron Client. Please take a look at this documentation, https://www.facebook.com/notes/simracingapps/electron-a-html-client-for-simracingapps/1566870046675409/

**Comment by jfgilliam** [comment]
If you don't have facebook, you can also get it at https://github.com/SIMRacingApps/SIMRacingAppsElectron
