### ISSUE TITLE
10/20 lap average(s)

### ISSUE THREAD

**Issue by StuntmanMichael** [SIMRacingApps/SIMRacingApps#111]
I would REALLY like to see 5, 10, 20 lap averages available on either a new widget or added to Broadcast, Spectator, or ANY of the relative or timing widgets. This is a VERY handy little piece of information in oval racing that is used extensively in real life. Currently no other app out there is doing this. It would be so awesome to be able to set X number of laps average. Meaning you'd have to complete at least X number of laps to get a result in the widget. However just having the 10 and 20 lap averages added to the broadcast widget would suffice as those are the ones used most often in real life. It could help aid in building long run setups or short run setups. Maybe even a short run average (5 laps) widget and so on and so forth. Just a thought.

**Comment by davidjvieira** [comment]
That would be real helpful when making long run setups.

**Comment by thomprl** [comment]
For me, I just would like to have green flag laps only.  After a yellow when the green comes out it would skip that lap but count the next one.  If coming out of pit road, do not count the out lap but count the next lap.  Same with practice, don't count the out lap.  It would be nice to know your best lap average range.  So if it's 10 lap average you could know that laps 10-20 were your fastest average.  

The main thing I would like to use it for is compare is maybe have all drivers in a practice on one of the relative/standings screens and be able to have a column for best x lap average.  So I could see maybe that guy has a fast 1 lap but he's slow over a run.   

Not sure if that makes sense or not.
