### ISSUE TITLE
PitCountDown and spotterpack

### ISSUE THREAD

**Issue by FrontSeatRacing** [SIMRacingApps/SIMRacingApps#112]
Is there a way to have for an example the JJ Spotter Pack to handle the countdown, I have heard that there is but I have not got it to work.

**Comment by FrontSeatRacing** [comment]
Got it working, these are my settings.

### Some known patterns to spotter packs. Your version may vary. 
### Double backslashes are required for the directory separator.
#####################################################################
pit-count-down-pattern = C:\\Program Files (x86)\\iRacing\\sound\\spcc\\JJ Spotter-Cuss Pack v6.70\\n%d.wav

#####################################################################
### These settings control how the audible pit speed limit beeper works.﻿

**Comment by jfgilliam** [comment]
Glad to hear. I let this one slip me by, sorry. Your example doesn't show double backslashes even though you say they are required?
