### ISSUE TITLE
None of the apps and wigets are  showing up

### ISSUE THREAD

**Issue by Langreegid** [SIMRacingApps/SIMRacingApps#113]
so I run the server download the leave it up and it is a whole bunch of codes on the little sever page but when I go in game it dosent show any of the icon

**Comment by Langreegid** [comment]
like any of the apps and wigets

**Comment by jfgilliam** [comment]
That's just the server. You have to pick a client to use. Sounds like you want https://github.com/SIMRacingApps/SIMRacingApps/wiki/How-to-setup-the-Electron-client

- Jeff

**Comment by Langreegid** [comment]
@jfgilliam so I know I saw it some where but how am I supposed to lanch electron

**Comment by Langreegid** [comment]
ok um so what is this mean like what browser                                                                Then, with SIMRacingAppsServer.exe running, connect to the Main Menu using your browser.
At the bottom of the menu, use the "Choose File" and "Upload" buttons and upload it. This will extract the files to "Documents\SIMRacingApps\electron-apps".

**Comment by jfgilliam** [comment]
That link gives you step by step instructions. But let me know if it can be improved. 

- Jeff

**Comment by jfgilliam** [comment]
Open IE or Chrome and type in the http address of the server 

- Jeff

**Comment by Langreegid** [comment]
@jfgilliam and where do u find the ip I'm sry I just don't know how to do all this stuff

**Comment by Langreegid** [comment]
ok I think I figured it out thx for your help
