### ISSUE TITLE
how do you change the graphics stuff   need help

### ISSUE THREAD

**Issue by Langreegid** [SIMRacingApps/SIMRacingApps#114]
ok so I went to note pad and realive I don't know how  to mess with that stuff and I didn't want to mess any thing up

**Comment by jfgilliam** [comment]
I think you can switch to windowed mode in the iracing options now. Otherwise, you'll need to call iracing for help in setting up windowed mode. 

- Jeff

**Comment by Langreegid** [comment]
so I went to not pad to change the stuff thet needed to be changed in the graphics but I don't know how to do any of that

**Comment by Langreegid** [comment]
ok thx

**Comment by Langreegid** [comment]
ok so I have done evry thing now I think so do I need to create a mapping for my screen now or do I need any thing else
