### ISSUE TITLE
Java Parameters -Xms -Xmx not overridden

### ISSUE THREAD

**Issue by samkatakouzinosracing** [SIMRacingApps/SIMRacingApps#118]
As per https://github.com/SIMRacingApps/SIMRacingApps/wiki/How-to-Define-Java-Parameters

I create an 'SIMRacingAppsServer.l4j.ini' file with the following parameters: -Xms1024m -Xmx1024m

When I launch SIMRacingAppsServer.exe in the same folder, Task Manager (Process or Details) shows the command line as having multiple instances of the parameters, that is: -Xms256m -Xmx512m -Xms1024m -Xmx1024m 
Memory doesn't seem to be changed in Task Manager either.

http://launch4j.sourceforge.net/docs.html#Additional_jvm_options states that "you can specify the options in the configuration file, ini file or in both, but you cannot override them". 

What do I need to do to override these values?

**Comment by jfgilliam** [comment]
The ini file must have the exact same name as the exe down to the version and date and reside in the same folder 

- Jeff

**Comment by samkatakouzinosracing** [comment]
The two files I mentioned above don't match?
I used literal file names in opening post (both ini and exe).

**Comment by jfgilliam** [comment]
Sorry, reading on my phone, I see that you can see the parameters in the task manager. That should have worked.

**Comment by jfgilliam** [comment]
post the ini file here, so I can verify it.

**Comment by samkatakouzinosracing** [comment]
SIMRacingAppsServer.l4j.ini;
```-Xms1024m -Xmx1024m```

**Comment by jfgilliam** [comment]
Try putting those options on separate lines
-Xms1024m-Xmx1024m
------------------------------------------------------
 Jeff


On Monday, August 14, 2017, 11:04:33 AM EDT, Sam Katakouzinos Racing <notifications@github.com> wrote:


SIMRacingAppsServer.l4j.ini;
-Xms1024m -Xmx1024m

**Comment by samkatakouzinosracing** [comment]
Command line shows as having multiple instances of the parameters, that is: -Xms256m -Xmx512m -Xms1024m -Xmx1024m

SIMRacingAppsServer.l4j.ini;
```
-Xms1024m 
-Xmx1024m
```

**Comment by jfgilliam** [comment]
Turns out Task Manager is not showing you the correct memory by default. You need to right click on the column header and select "Commit Size".

![image](https://user-images.githubusercontent.com/5891428/29298398-4aeb965c-8135-11e7-9f7a-5f04265ace3f.png)

**Comment by samkatakouzinosracing** [comment]
@jfgilliam thank you for the directions. 
I can see the changes through the 'Commit Size' column now. 
It appears the memory configuration changes do propagate correctly.

**Comment by jfgilliam** [comment]
let me know if this actually helps you.
