### ISSUE TITLE
Feature: Setup Protector

### ISSUE THREAD

**Issue by thomprl** [SIMRacingApps/SIMRacingApps#137]
When IsInGarage = 1 have the ability to display a image over the top of the setup screen to be used for Streams.

**Comment by jfgilliam** [comment]
I think I will create a new widget that will display the image found at Documents\SIMRacingApps\InGarage.png. If no image is found, the a gray screen will be displayed, unless you make it transparent.

**Comment by thomprl** [comment]
Just discovered the Waiting for Sim widget, wondered if you might could leverage that one?  Have a different image for each different setting.  Just an idea and might not be any hard or easier.

**Comment by jfgilliam** [comment]
I'll probably copy that one. I'll need to add a new API call for the garage.
------------------------------------------------------
 Jeff 

    On Saturday, January 13, 2018, 2:14:01 PM EST, thomprl <notifications@github.com> wrote:  
 
 
Just discovered the Waiting for Sim widget, wondered if you might could leverage that one? Have a different image for each different setting. Just an idea and might not be any hard or easier.

**Comment by jfgilliam** [comment]
Didn't need a new API call, I used Car/ME/Status = INGARAGE. It will be included in SRA Server version 1.6

**Comment by thomprl** [comment]
I thought of one more thing that would be a nice to have on this.  Is there a way to play a sound at least at the showing and maybe at the hiding of the image?  Reason is if you don't have your stream (XSplit or OBS) preview where you can see it, it would be nice to nice to know ok the screen is display because there is a small delay.  

Also might be nice for the Waiting for Sim as well.  

Very low priority

**Comment by jfgilliam** [comment]
How long is the delay. I have it set to 1000ms.
------------------------------------------------------
 Jeff 

    On Tuesday, January 16, 2018, 3:11:05 PM EST, thomprl <notifications@github.com> wrote:  
 
 
I thought of one more thing that would be a nice to have on this. Is there a way to play a sound at least at the showing and maybe at the hiding of the image? Reason is if you don't have your stream (XSplit or OBS) preview where you can see it, it would be nice to nice to know ok the screen is display because there is a small delay.

Also might be nice for the Waiting for Sim as well.

Very low priority

**Comment by thomprl** [comment]
It's not long, probably 1 sec or 2.  But long enough that you could click on chassis settings.  I thought the sound might help you know the screen should be displayed and you could continue on.

**Comment by thomprl** [comment]
Here's a link showing my stream

[](https://youtu.be/F4vinZIVNWY?t=376)

**Comment by jfgilliam** [comment]
Go into the .js file and change the interval to 100
------------------------------------------------------
 Jeff 

    On Tuesday, January 16, 2018, 3:28:58 PM EST, thomprl <notifications@github.com> wrote:  
 
 
Here's a link showing my stream

**Comment by thomprl** [comment]
That seemed to help.

**Comment by jfgilliam** [comment]
That's probably going to have to do it. I don't know how the server can know when the widget has displayed the image. That's the only way you can hear it. If the widget generates the sound, that's on the XSplit client and I assume would only go out on the stream and you couldn't hear it.
