### ISSUE TITLE
Detect to display Laps or Time Remaining on all widgets

### ISSUE THREAD

**Issue by jfgilliam** [SIMRacingApps/SIMRacingApps#139]
Change all widgets to detect either Laps or Time remaining based on which one will occur first.

Suggested by @thomprl

**Comment by thomprl** [comment]
It might be nice to have the lap number but I’m not sure if that should be your lap number or the leaders lap number. Since cars will be on multiple laps.

**Comment by jfgilliam** [comment]
Standings, Relative, LapTiming, CrewChief, Digital Dash were modified to show the approximation of laps remaining and/or the time remaining.
