### ISSUE TITLE
Pit road countdown not working in league session

### ISSUE THREAD

**Issue by gshldon** [SIMRacingApps/SIMRacingApps#142]
I just installed simapps, so far I mainly use the pitroad adjustments and pitstall countdown, they work in practice and in the official races, but I ran in 3 different league races, and it did not work in any of them, I did restart the server and everything before each league race and it would not work, any ideas?

In Iracing...

**Comment by jfgilliam** [comment]
There was a bug reported just this week about league admins putting invalid characters in the driver's name causing SRA to crash. You should see the problem in the Documents\SIMRacingApps\logs. I'm going to post a BETA version that fixes it in a day or 2. Still testing it.

**Comment by jfgilliam** [comment]
Fixed in BETA version Version_1.6_Build_BETA-2018.02.01. Download now at http://downloadsBETA.SIMRacingApps.com
