### ISSUE TITLE
Store the lowest & highest positions per driver/class

### ISSUE THREAD

**Issue by thomprl** [SIMRacingApps/SIMRacingApps#152]
The ability to store the lowest and highest positions a car has been in the race either by overall or class.  Also if possible the position either they restarted in after a caution and/or maybe the position they came out after a pit stop?  Not sure on that one that might get to messy to try and figure out.  Trying to keep up with positions gained/lost.

**Comment by jfgilliam** [comment]
Added these to the API in the first 1.7 BETA
/Car/(CARIDENTIFIER)/PositionLowest
/Car/(CARIDENTIFIER)/PositionHighest
/Car/(CARIDENTIFIER)/PositionLowestClass
/Car/(CARIDENTIFIER)/PositionHighestClass
