### ISSUE TITLE
REFERENCE car should follow who the camera has selected

### ISSUE THREAD

**Issue by thomprl** [SIMRacingApps/SIMRacingApps#153]
If using something like DriverInfo widget, and using REFERENCE as the car selected it should follow who the camera is actually own if possible.

**Comment by thomprl** [comment]
If this is possible, will it like on the track map, can I say reference car and leader and as the camera switches it shows that on the track map.  That way I can show only 2 cars on the map at a time.  It gets a little cluttered at times.  Thanks.

**Comment by jfgilliam** [comment]
I started working on this and I found I had it in the code at one time and I commented it out. Knowing my memory, I should have documented why I did that :). The only thing I can think of is how the camera focus changes when you select follow Crashes or Exciting. Do you still want it to follow it? I think I will add a settings value to turn it on or off as well (reference-camera = Y)

**Comment by thomprl** [comment]
It would be nice it you could implement it. The main reason I wanted it was to turn it on the most exciting and let it show information about who the camera was pointed too.

**Comment by jfgilliam** [comment]
OK, I put the code back in and it's is working fine. It will be in the next 1.7 BETA release
