### ISSUE TITLE
Per Car Widgets

### ISSUE THREAD

**Issue by BadBoyClub** [SIMRacingApps/SIMRacingApps#155]
Ability to only use certain widgets with certain cars

i.e.; I want to use the 'gear display widget' for stock cars, but not for the Porsche as it is superfluous. Possibly via settings file?

**Comment by jfgilliam** [comment]
You can use multiple configurations in Electron for each car or car type

**Comment by jfgilliam** [comment]
Hope my previous comment met your needs. I'm closing this issue.
