### ISSUE TITLE
Fuel Widgits - Incorrect fuel units on Porsche 919

### ISSUE THREAD

**Issue by MirrorImageQS** [SIMRacingApps/SIMRacingApps#171]
In the Porsche 919, the fuel widgit has some unusual behavior around choosing the correct unit. See the attached zip with video demonstrating the issue.
[SRA Porsche 919 fuel.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/2125656/SRA.Porsche.919.fuel.zip)

- On loading the sim initially, the widget defaults to Gallons, which is otherwise correct for my settings.
- The widget does not respond to the Metric checkbox to switch between Gallons and Liters.
- Upon entering the car for the first time, the widget changes to using Pounds (Lbs) or Kilograms (Kg), depending on metric setting, and does not change back. The numbers are otherwise accurate in that unit.

I believe this could be caused by the fact that this car originally used Pounds and Kilograms when it was initially released, but shortly afterwards, it was switched to using Gallons and Liters.

**Comment by jfgilliam** [comment]
Thanks for bringing this to my attention. I don't run this car, so I didn't notice the change. Attached is a new profile for the car. Download it, then rename it to "prosche919.sra". At the bottom of the SRA menu, choose the file and upload it. Restart the server. Let me know if it works.


[porsche919.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/2125875/porsche919.zip)

**Comment by MirrorImageQS** [comment]
Works correctly now. Thanks.
