### ISSUE TITLE
Port not shown in window title

### ISSUE THREAD

**Issue by samkatakouzinosracing** [SIMRacingApps/SIMRacingApps#177]
https://github.com/SIMRacingApps/SIMRacingApps/wiki/Port-80-in-use-by-another-process states the following;

> Take note of the port it found in the title of the server's window pane.

This no longer holds true. 
I've created a test case where nginx server occupies ports 80 and 8080 and no server occupies port 5555.
The window show no port at all. 

Please make this work again as it is useful.

**Comment by jfgilliam** [comment]
Sam, when it doesn't show a port, it is using port 80. Did you try to connect to it?

**Comment by samkatakouzinosracing** [comment]
> Sam, when it doesn't show a port, it is using port 80. Did you try to connect to it?

Yes. Whether port 80, 8080, 5555 it does not show the ":xxxx" port added to the ip address.
I use nginx and alter the single or multiple ports it uses to test SRA.
