### ISSUE TITLE
Pit stall position audio warning

### ISSUE THREAD

**Issue by BadBoyClub** [SIMRacingApps/SIMRacingApps#191]
Add an audio warning to tell you you're 'too far forward / back / to the left / right' after entering your pit stall. 

We get a display on the monitor to tell is, is it possible to add this as an audio warning similar to how we have the pit countdown?

**Comment by jfgilliam** [comment]
That would be a good feature. But, that level of detail is not in the telemetry. According to the telemetry, you are still in your pit stall when those messages come up. I'll leave this on the list, though.



- Jeff Gilliam


-------- Original message --------

**Comment by thomprl** [comment]
I sent David a note about this several days ago but haven't gotten a reply yet.  Would be nice to have a spotter call as well.

**Comment by thomprl** [comment]
http://members.iracing.com/jforum/posts/list/3150/1470675.page#11474187

**Comment by jfgilliam** [comment]
In the 3/19/2019 patch, iRacing added this.

From David,
I am adding in a new enum "PlayerCarPitSvStatus" that is set to one of the following: In the future I could look into expanding this to cover towing and other status indicators.

enum irsdk_PitSvStatus
{
// status
irsdk_PitSvNone = 0,
irsdk_PitSvInProgress,
irsdk_PitSvComplete,

// errors
irsdk_PitSvTooFarLeft = 100,
irsdk_PitSvTooFarRight,
irsdk_PitSvTooFarForward,
irsdk_PitSvTooFarBack,
irsdk_PitSvBadAngle,
irsdk_PitSvCantFixThat,
};
