### ISSUE TITLE
Repair timers reset in replay window

### ISSUE THREAD

**Issue by thomprl** [SIMRacingApps/SIMRacingApps#193]
While you are getting damage fixed if you go to the replay window the timer resets to zero so you can’t watch how much time is required to repair your car and continue watching the race.

**Comment by jfgilliam** [comment]
In testing this fix, it works as long as you don't change the camera to another car. You can always come back to your car to see it. That's because the server changes everything to the car in focus.

**Comment by thomprl** [comment]
Ok, I didn't think about that.  I'll try to remember that.
