### ISSUE TITLE
Pit Count Down Sound: add the new pit statuses (left,right,front,back)

### ISSUE THREAD

**Issue by jfgilliam** [SIMRacingApps/SIMRacingApps#196]
In the 3/19/2019 patch, iRacing added this. Make use of it somehow.

I am adding in a new enum "PlayerCarPitSvStatus" that is set to one of the following: In the future I could look into expanding this to cover towing and other status indicators. 

enum irsdk_PitSvStatus 
{ 
// status 
irsdk_PitSvNone = 0, 
irsdk_PitSvInProgress, 
irsdk_PitSvComplete, 

// errors 
irsdk_PitSvTooFarLeft = 100, 
irsdk_PitSvTooFarRight, 
irsdk_PitSvTooFarForward, 
irsdk_PitSvTooFarBack, 
irsdk_PitSvBadAngle, 
irsdk_PitSvCantFixThat, 
};

**Comment by thomprl** [comment]
It would be nice to have either 4 sounds or at least 1 sound with someone saying either You are not in your pit box, or You are too far left, right, forward or back.

**Comment by jfgilliam** [comment]
See #191
