### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by Nocovabby** [SIMRacingApps/SIMRacingApps#200]
Hi, I have an issue, when I try to run new version of SRA, I see the terminal wirth "could not find or load main class com.SIMRacingApps.server" 

This never happened before and I checked if Java was up to date, and it is. 

Can somebody give me a hand ? 

Thanks a lot
![bandicam 2019-04-20 23-42-33-292](https://user-images.githubusercontent.com/49821931/56462588-fa445480-63c5-11e9-9441-5cd0f63f393d.png)

**Comment by jfgilliam** [comment]
Check the file size. Should be about 200mb. If not, try downloading it again

- Jeff
