### ISSUE TITLE
GForce Widget

### ISSUE THREAD

**Issue by gp66** [SIMRacingApps/SIMRacingApps#201]
2D GForce Map
[GForce.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/3144948/GForce.zip)

**Comment by jfgilliam** [comment]
I took a look at your code and I only have one recommendation. Change the author to your name and give yourself some credit for an excellent widget. The zip file is correctly formatted, so just rename it GForce.sra and upload it to the Files section. With your permission, I will add it to the next release.

**Comment by gp66** [comment]
I uploaded the sra file before reading this and think it's cool the app will make it to the next version. Besides the simple calculations, I followed examples from many other widgets and several 'very helpful' lessons. I need to hit the books on angular, still pretty lost on how it works, DOM, etc. I'm already digging into my next app, i will try not to bug you... too much. :)

**Comment by jfgilliam** [comment]
I release the 1.10 BETA with your widget in it. I made the 2 new vars part of the API. I also added the UOM conversions. If you want to modify it, please update this version of it and send it to me.

https://github.com/SIMRacingApps/SIMRacingApps/releases/tag/Version_1.10_Build_BETA-2019.05.18

**Comment by gp66** [comment]
no modifications, everything looks great. The more i play with SRA the more blown away I am with what's under the hood! I'm finishing up an F1 style compteur like the one found in jrt overlays and would like your opinion before I share with community.Will send it in a Facebook message. 

Pretty cool seeing my widget in the official build :)
