### ISSUE TITLE
API : CORS issue

### ISSUE THREAD

**Issue by bastienmp** [SIMRacingApps/SIMRacingApps#205]
Hello 

I think it would be great if the server could handle CORS headers : https://developer.mozilla.org/fr/docs/Web/HTTP/CORS
it would avoid some bug with chrome like :
- sending a simple message with a request to /Car/(CARIDENTIFIER)/Messages/ is received twice : once as a OPTIONS request, once for the GET request, which result in a message send twice !
- To develop a simple React.js app, i need to install a chrome plugin do disable CORS checking.

Thanks for the amazing work, 
Bastien

**Comment by jfgilliam** [comment]
My philosophy has been to not rely on the availability of external web sites to load libraries. To implement CORS, I have to list the sites in the headers. Instead put libraries, like React.js, as a local copy. Just put it in documents/simracingapps/external and load it from there. This has to be done as an App, not a widget.

**Comment by jfgilliam** [comment]
Was just thinking, as an App, you can add your own headers in the html

**Comment by bastienmp** [comment]
Thanks for the quick answere !
