### ISSUE TITLE
Issue with getting DiffCarsRelative data for 2 cards using Id or Position as carId

### ISSUE THREAD

**Issue by iamisti** [SIMRacingApps/SIMRacingApps#206]
Either the documentation is wrong, or something is not working properly.
Method: http://simracingapps.com/docs/JavaDoc/com/SIMRacingApps/Session.html#getDiffCarsRelative-java.lang.String-java.lang.String-

When i'm trying to get the relative distance between Car1 and Car2, it always results to 0 if i try to use the following car id:
Ixx
PCxx

Example: 
/DiffCarsRelative/PC1/PC2 does not work

using leader or reference works (although not with every carId combination). But I really want to compare the distance of 2 cars regardless where they are and not necessearly compared to leader or to the reference.

Note: Pxx also works

**Comment by jfgilliam** [comment]
Even though I, P and PC are based on scoring positions, I added them to this API so they would work. Look for this to be fixed in the next BETA dated after 2019.08.10.

**Comment by iamisti** [comment]
thank you!
