### ISSUE TITLE
Add Realtime iRating to Standing Widget

### ISSUE THREAD

**Issue by KennyPowell** [SIMRacingApps/SIMRacingApps#209]
I would like to help with adding a column to the Standings widget that would show your Realtime iRating based on your current position in the race.  I have the formula but don't know where to start in the collaboration to make it a reality

**Comment by jfgilliam** [comment]
That would have to be put in on the sever side. What is the formula?

- Jeff

**Comment by KennyPowell** [comment]
As I'm sure you know.  It's not a simple formula and a lot of info has to
be gathered and processed just to be able to put the pieces together to
arrive at the correct number.  Here is an excel spreadsheet to break it
down.  Be sure to unhide all the columns to the right to see the real meat
of it.

Thank you,
  Kenny Powell

**Comment by jfgilliam** [comment]
Looks like GitHub did not keep the attachment. You can email it directly to support@simracingapps.com. If you prefer to keep it private, let me know. Else, I'm going to attach it to this issue.

**Comment by KennyPowell** [comment]
[iRacing SOF iRating Calculator v1_1.xlsx](https://github.com/SIMRacingApps/SIMRacingApps/files/3617438/iRacing.SOF.iRating.Calculator.v1_1.xlsx)

**Comment by jfgilliam** [comment]
To turn this off add this to the settings.txt file.

dynamic-irating = N
