### ISSUE TITLE
PATH = /Session/IsGreenFlag is only true on the first lap after caution.

### ISSUE THREAD

**Issue by KennyPowell** [SIMRacingApps/SIMRacingApps#210]
getIsGreenFlag
public Data getIsGreenFlag()
Returns true if the green flag is waving.
PATH = /Session/IsGreenFlag

Returns:
true if the green flag is out in a Data container.

**Comment by jfgilliam** [comment]
According to iRacing that’s the only time the flag is waved. 

- Jeff

**Comment by jfgilliam** [comment]
Closing. In 1.12 a new API path, /Session/Status, was added to accommodate this request.
