### ISSUE TITLE
program will not start

### ISSUE THREAD

**Issue by jtrain222** [SIMRacingApps/SIMRacingApps#215]
I just updated to the new build and it will not allow me to use the program

**Comment by jfgilliam** [comment]
Are you getting any error? If so, can you share a screen shot? 
Does the previous version still work?

**Comment by jtrain222** [comment]
I can use 1.11 build. On the 1.12 build I go to start it like I've always done and it will try to start and go through all the settings and when the app normally opens it'll say exiting.

**Comment by jfgilliam** [comment]
Please run 1.12 and after it exits, upload your logs from the Documents/SIMRacingApps/logs folder.

**Comment by jtrain222** [comment]
I went and reinstalled java and that has fixed this issue.

**Comment by jfgilliam** [comment]
Glad you figured it out.
