### ISSUE TITLE
Leader Telemetry

### ISSUE THREAD

**Issue by ToteFarms** [SIMRacingApps/SIMRacingApps#228]
When I use the Leader Tememetry it shows RPM and Speed but does not show throttle and Brake. It will show throttle and brake if the reference car si me, and it shows throttle and  brake if I am the leader. I t doesn not show throttle and brake if another car is the leader just sped and RPM.
![Leader Telemetry2](https://user-images.githubusercontent.com/65742145/85926128-d2227200-b862-11ea-9075-210804fad70a.PNG)
![Leader Telemetry2](https://user-images.githubusercontent.com/65742145/85926134-dcdd0700-b862-11ea-8024-63100a33c1d5.PNG)

**Comment by jfgilliam** [comment]
IRacing doesn’t provide those values for any of the other cars.
