### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by Racefan388** [SIMRacingApps/SIMRacingApps#230]
I download the exe file. run it. the first page starts running, then stops. And at the bottom I get Warning: C:\Users\New PC\OneDrive\Documents|SimRacingApps\electron-apps\electron\SimRacingApps-electron.exe not found: com.SIMRacingApps.Server.main(Server.java:1040)[main]

**Comment by jfgilliam** [comment]
Remove this folder and restart. 

> C:\Users\New PC\OneDrive\Documents|SimRacingApps\electron-apps
> 

- Jeff

**Comment by Racefan388** [comment]
Thank you very much. That worked.
