### ISSUE TITLE
No 'drive through' penalty in Race Administrator App

### ISSUE THREAD

**Issue by verybadracer** [SIMRacingApps/SIMRacingApps#231]
Hi All,

It has been release in the latest patch a 'drive through' penalty. Which is now fast becoming the standard starting penalty in managed races.

I currently use the race administrator widget to manage races and I love it, however drive through is sadly missing.

The new command for a drive through is '!black #number D' the 'D' denoting the new pen.

Is there any way of this being added to the current widget, or alternatively, is anyone able to instruct me on how I may go about adding this command in myself to the widget on the back end?

Many thanks!

**Comment by jfgilliam** [comment]
Would you be willing to give up the Black Flag 1 Lap button?

**Comment by verybadracer** [comment]
Absolutely, it's a rarely used penalty nowadays! Thanks for getting back to
me so quickly it's much appreciated

**Comment by jfgilliam** [comment]
Just release the BETA version with this change in it. Let me know how it works.
http://downloadsbeta.simracingapps.com
- Jeff 

    On Thursday, July 30, 2020, 12:34:15 AM EDT, verybadracer <notifications@github.com> wrote:  
 
 

Absolutely, it's a rarely used penalty nowadays! Thanks for getting back to
me so quickly it's much appreciated
