### ISSUE TITLE
Fuel widget not working

### ISSUE THREAD

**Issue by brendanbook** [SIMRacingApps/SIMRacingApps#233]
We spotting or being the the crew chief for someone, I am unable to see any information about the driver's fuel. The fuel widget is just blank. Works perfectly fine for myself. Not sure if you'd be able to fix that.

**Comment by jfgilliam** [comment]
I can’t fix. IRacing doesn’t put it in the telemetry. Many app creators have complained in the forums. 

- Jeff

**Comment by brendanbook** [comment]
Damn. Okay, thank you.
