### ISSUE TITLE
Widgets fail to work with UI

### ISSUE THREAD

**Issue by kdb29** [SIMRacingApps/SIMRacingApps#234]
I've been using the UI really for the first time this week and although my widgets work fine from the website, they are very glitchy and only update periodically with the UI. The server app also just looks like a flood of text as if it's trying to compute a lot more information than when you start a race from the website. Not sure if AI racing is the cause.

**Comment by jfgilliam** [comment]
Please attach your logs from Documents/Simracingapps/logs

- Jeff

**Comment by kdb29** [comment]
[SIMRacingApps-2.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/5208547/SIMRacingApps-2.log.txt)
Here's the last log file in the directory.

**Comment by jfgilliam** [comment]
Is this still happening after the hot fix today.?  The release notes indicated an issue with the car number. That’s what I see in your log. 


- Jeff Gilliam

**Comment by kdb29** [comment]
It is working fine again! Hadn't seen it before and thought it was odd it only happened in one environment, but all sorted out now. Thanks for looking into it!
