### ISSUE TITLE
Four Monitors

### ISSUE THREAD

**Issue by 7time** [SIMRacingApps/SIMRacingApps#236]
It's working now but can't get to work with my four monitors in surround, can you help ?????  Other than that I love it.
Was using Z! Dashboard no more this programs beats anything I have ever seen.

**Comment by jfgilliam** [comment]
No need to post in 3 places

**Comment by 7time** [comment]
I have four monitors I have three lower monitors and a top monitor

I want to run Sim Racing apps On top do you know how to do this,

just wanted how '


Sincerely

Robert Lutz
(414) 484-8441)
 shadowmotorsports@gmail.com

**Comment by jfgilliam** [comment]
Turn the frame on for the app to move. Launch it, Move it, resize it, turn the frame off. Check load on startup.


- Jeff Gilliam
