### ISSUE TITLE
TireCompound API

### ISSUE THREAD

**Issue by jfgilliam** [SIMRacingApps/SIMRacingApps#237]
iRacing now outputs your tire compound in the telemetry. Add to the API and possible some of the widgets. Also make it a text widget.

@Linus Areng suggested this.

My thoughts and notes:

It probably should be part of the Gauge design. Tire attribute for sure. What other gauges would need a similar attribute? What would a good generic name be? So, if a gauge is changeable, like tires, you get to choose it as well.

Should act like a tire measurement, similar to the temps and pressures?

iRacing puts out these arrays in the vars that returns an enumerated number:

CarIdxTireCompound
CarIdxQualTireCompound
CarIdxQualTireCompoundLocked

Haven't found the enum in the SDK, but here's my guess.
0 = SOFT
1 = MEDIUM
2 = HARD

Need to learn more about how they are used/controlled in a Race. Maybe the ability to choose prior to pitting in the PitController widget.

**Comment by linusareng** [comment]
Hey, cheers for looking at adding it.
They way I'd personally looking to use this info is in a standings and/or relative widget where the information about what tyre compound the cars around me have which will influate both my driving at the moment as well as race strategy.

Other people might look to use it differently, but that's my usecase.

**Comment by jfgilliam** [comment]
Tell me more about how you choose. I've never run a race where this was an option. Is it something you have to choose before the race and/or qualifying? Or can you choose each time you pit to put on a different compound? Can you choose in a practice session? Are your choices different based on the track? Is the a count limit of each type?

**Comment by linusareng** [comment]
How it works is that you have to start with the tire you qualify with. This is enforced and that's why you see the CarIdxQualTireCompoundLocked var. 
So you choose a qualifying tire in the garage settings, and after you've set a time on that tire it is locked in as your race start tire.

Then while racing, you choose in a black box which tire you'd like to switch to when pitting. Soft, medium or hard. 
Soft are the quickest tire, but don't last long in the race. 

In the races there are a variety of strategies playing out, and some people are easier on their tires making them last longer which can be a great advantage.

**Comment by jfgilliam** [comment]
Ok, that helps a lot. iRacing has an API where I can send messages to them on what to do on your next pit. I saw someone asked in the forums to have the API amended with the ability to choose the tire compound as well. So, apparently it can only be chosen in their black box at the moment. Nothing new for them. They don't give much attention to this API and it generally lags in features. Some are still not there for many years in the API, such as, Wedge adjustments.

So that it doesn't take much room on the widgets, would simply displaying S,M,or H be sufficient?

**Comment by jfgilliam** [comment]
![image](https://user-images.githubusercontent.com/5891428/95987853-fdbb6f00-0df5-11eb-8267-727f06fd4356.png)

**Comment by jfgilliam** [comment]
I wonder if iRacing will use this when they get around to rain tires? I'm going to post a question on the forums.

**Comment by linusareng** [comment]
For myself personally S, M and H would be sufficient or even preferred, F1 people will know and don't need the full name. 
And as a color blind person I can have a hard time seeing what tires are in use at the moment if images or solely colors are used. iRacing themselves use small tire images to show which tire a person is on (visible in "Entries" tab in sim). This is hard to discern for me.

I think they'll definitely use this for other compounds, such as rain tires, going forward.
Tires are red, yellow or white (soft, medium, hard).

**Comment by jfgilliam** [comment]
![image](https://user-images.githubusercontent.com/5891428/96012044-b5aa4580-0e11-11eb-898d-2f637cda434e.png)

**Comment by jfgilliam** [comment]
![image](https://user-images.githubusercontent.com/5891428/96029394-9965d300-0e28-11eb-8625-6248f4193f7b.png)

**Comment by jfgilliam** [comment]
![image](https://user-images.githubusercontent.com/5891428/96138391-bacbcb00-0ecb-11eb-83aa-2579a4a5a35b.png)

**Comment by jfgilliam** [comment]
Can you provide a list of all the cars that have this option that you know of?

**Comment by jfgilliam** [comment]
I also just observed that the PitSv variables to not indicate the Tire Compound selection for your next pit stop. So, until they add that, I can only display what's on the car after you pit.

![image](https://user-images.githubusercontent.com/5891428/96139613-05017c00-0ecd-11eb-95cb-b485719d3f15.png)

**Comment by linusareng** [comment]
Only the McLaren MP4-30 so far has the tire compounds.

**Comment by linusareng** [comment]
How quickly do you usually add these kind of things out of  curiosity? 
Not to rush you at all, I just want something to look forward to and have a rough sketch if it is within next week, before new years or sometime later. A beta branch/release would be fine, added everything else I want on my widget just the tires missing :)

**Comment by jfgilliam** [comment]
Something this easy, a couple of weeks. I’ve slotted it for the next beta. 


- Jeff Gilliam

**Comment by jfgilliam** [comment]
new API is

/Car/(CARIDENTIFIER)/Gauge/TireCompound

Had to make ValueNext return ValueCurrent as iRacing is not logging in the telemetry what you have selected in the black box.

Updated the Tire and TireMeasurements widgets to display it.

This will be released in the 1.15 first BETA soon.
