### ISSUE TITLE
Information about iRacing tracks

### ISSUE THREAD

**Issue by deogonit** [SIMRacingApps/SIMRacingApps#242]
Thank you for your work and application. I want to create a small application in Python which will take telemetry from iRacing. Today, I have found that iRacing doesn't give us information about gps coordinates of cars. iRacing give only value of percentage distance around lap (0.0, 0.1, 0.2). It's  **CarIdxLapDistPct** value. 
In project repository I've found files about general tracks information. For example,  [this file](https://github.com/SIMRacingApps/SIMRacingAppsServer/blob/master/src/com/SIMRacingApps/Tracks/lakeland.json) have information about USA International speedway. So, I have question about how you get the information about tracks? Could you please share this method?

**Comment by jfgilliam** [comment]
This was no small feat. 

In the following folder, you find all the track information I have.

https://github.com/SIMRacingApps/SIMRacingAppsServer/tree/master/src/com/SIMRacingApps/Tracks

The GPS coordinates is available in the disk telemetry. So, my first round, to get this information, was to actually drive around the track while the telemetry logging was turned on. Then I wrote a small program to extract the coordinates and the percentage out of the .IBT file it creates. I stored those in the .json files in this folder.

Then I found a better approach. I used a website, http://www.gpxeditor.co.uk, to create a route of the track. Then I was able to calculate the GPS from the percentage. The code to do that, can be found here.

https://github.com/SIMRacingApps/SIMRacingAppsServer/blob/master/src/com/SIMRacingApps/Track.java

Then, on the client side, there's a .js library that maps the coordinates onto an image. That code is found here.

https://github.com/SIMRacingApps/SIMRacingAppsWebContent/blob/master/widgets/TrackMap/TrackMap.js

Now that you know this, my recommendation would be to use my server to extract the information you need via API ReST calls. I've done all the hard work for you. :)

**Comment by deogonit** [comment]
Thank you for your quick response and help. I've never knew that iRacing can save telemetry information about car in separate file. The next step will be parsing data from this file. So, I guess you can close the issue. Thank you again!
