### ISSUE TITLE
CarImage don't show correctly if user has a paint with a custom number

### ISSUE THREAD

**Issue by Scar7752** [SIMRacingApps/SIMRacingApps#243]
I see cars with normal paints load correctly, but if someone has a paint with a custom number (car_num_[custid].tga) it doesn't load the paint through the CarImage widget

**Comment by jfgilliam** [comment]
Thanks, how does this work? In hosted only? Wouldn’t think it could be used in a normal session.

**Comment by jfgilliam** [comment]
Found this on the forums. Seems to indicate only works in test sessions?

![image](https://user-images.githubusercontent.com/5891428/111638297-92286400-87d0-11eb-9e5d-2915308d15f2.png)

**Comment by Scar7752** [comment]
It works in any session, not just testing. 

How it works is if you set that to I think 1 then load like a carb cup session, you'll see people with paints that don't match their actual number. It's good for league and hosted racing.

**Comment by jfgilliam** [comment]
Ok, for now, I think I'll just honor that setting. Then we need to limit it to certain sessions.

**Comment by jfgilliam** [comment]
You can download the 1.16 BETA to get this fix.

http://downloadsbeta.simracingapps.com
