### ISSUE TITLE
CameraSelector Names Overlapped?

### ISSUE THREAD

**Issue by DaKicker8** [SIMRacingApps/SIMRacingApps#249]
Hello. I just downloaded SimRacingApps and am planning to use it mainly for broadcast purposes. I opened the camera selector and this is what I keep seeing. This is also occuring on the CameraSelector30 and vertical versions as well as the RaceAdministrator
![Screenshot 2021-04-20 212828](https://user-images.githubusercontent.com/82923077/115492643-62310e00-a21f-11eb-8af1-5922d1fee80e.png)

**Comment by jfgilliam** [comment]
On the main menu, in the documentation section, select useroverrides.css. Add the following. Then save and refresh the widget.
.SIMRacingApps-Widget-CarNumberExtended-name {    text-shadow: 1px 0 0 #000, 0 -1px 0 #000, 0 1px 0 #000, -1px 0 0 #000;
}

- Jeff 

    On Tuesday, April 20, 2021, 11:29:05 PM EDT, DaKicker8 ***@***.***> wrote:  
 
 


Hello. I just downloaded SimRacingApps and am planning to use it mainly for broadcast purposes. I opened the camera selector and this is what I keep seeing. This is also occuring on the CameraSelector30 and vertical versions as well as the RaceAdministrator

**Comment by DaKicker8** [comment]
Apologies for the late reply as I have been extremely busy as of late. I'll make sure to try that tomorrow or Saturday and update!

**Comment by jfgilliam** [comment]
No problem. I also have this queued up to be fixed in the next BETA release.
- Jeff 

    On Friday, April 23, 2021, 12:34:58 AM EDT, DaKicker8 ***@***.***> wrote:  
 
 


Apologies for the late reply as I have been extremely busy as of late. I'll make sure to try that tomorrow or Saturday and update!

**Comment by DaKicker8** [comment]
Fixed!

**Comment by jfgilliam** [comment]
Yes, open a new one unless it's related.

**Comment by DaKicker8** [comment]
It is not. Thank you!
