### ISSUE TITLE
Chat Button Widget

### ISSUE THREAD

**Issue by jfgilliam** [SIMRacingApps/SIMRacingApps#25]
Create a chat button widget that take as an argument the button name. The text for the button and the string to send to the SIM can be defined in the settings.txt file.

Example:

chat-button-1 = Pass Low;Pass Low[ENTER]

NOTE: The SIM's Plugin will be responsible for setting itself up to receive the key strokes as a text message. This is not designed to send arbitrary commands to the SIM to get it to do something else. (Or should it?)

Create a predefined widget with 9 buttons with some default values. Add those defaults in the code and in the default.settings.txt file.

Possibly have a way to send the message to a specific car. Maybe start the key name with an "@NUMBER=" atsign and the word number to indicate you want the car number from the car "R-1" to be placed in the text at that point.

chat-button-1 = Pass Low;/[@NUMBER=R-1] Pass Low[ENTER]

**Comment by jfgilliam** [comment]
added in version 1.0_Build_BETA-2016.04.25. Actual implementation not exactly as the request. See help for more accurate details.

**Comment by AttilaPappJr** [comment]
Hi Gilliam,

I'm new here and just found your great app.
The most useful widget for me would be the Chat app, but for some reason I cannot modify the buttons in the settings.txt file.
I can only modify the four lines already included:
chat-row1-col1-name = PASS LEFT
chat-row1-col1-text = /RL-1 Pass Left
#chat-row2-col1-name = PASS RIGHT
#chat-row2-col1-text = /RL-1 [#[CARNUMBER]] Pass Right

If I modify the PASS LEFT to anything else, it works.
But if I want to modify for example the 2nd button by adding new rows:
"chat-row1-col2-name = DUMMY
chat-row1-col2-text = /RL-1 Dummy text for you"
This is not working, the button stays with the original "GOOD LUCK" text.

Sorry if I put this to a wrong place, or if I'm using wrong code, I couldn't find the proper way in the description, and I have only limited knowledge of programming.

Many thanks

**Comment by jfgilliam** [comment]
The best place to ask questions like this is on the SIMRacingApps Facebook group.

I put your example in my settings.txt and it worked. Here's what is looks like:

chat-row1-col2-name = DUMMY
chat-row1-col2-text = /RL-1 Dummy text for you

If yours really has the quotes around it as shown, then that's why it's not working. Another reason could be you need to restart the server and refresh the Chat app on the device you're running it on. 

If this doesn't help, join the group and upload your settings.txt file to it and I will look at it.

**Comment by AttilaPappJr** [comment]
I didn't have the quotes in it, and have restarted the server. Maybe the problem was that I didn't refresh the chat browser window? Will try that, thx for the tip.
I've joined the fb group already, will post there if I run into issues again.
Many thanks for your help
