### ISSUE TITLE
AdminController buttons won't work

### ISSUE THREAD

**Issue by DaKicker8** [SIMRacingApps/SIMRacingApps#251]
Hello, I was running into another problem with SimRacingApps where I would attempt to use the black flag or EOL buttons but they would not register in iRacing. The caution command worked just fine. I've only had problems with the buttons below the first row

**Comment by DaKicker8** [comment]
Yes, I have done that when attempting to use those buttons but they would
not register in the race although it displayed that it sent the command

**Comment by DaKicker8** [comment]
[SIMRacingApps-2.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/6462818/SIMRacingApps-2.log.txt)

This was one of the days I was testing the black flag on 177. Though they never received one

**Comment by jfgilliam** [comment]
Thanks. I can see the commands in the log that means the app is recognizing your clicks properly and the serve is receiving them. I’m assuming the syntax of the commands are correct. You can try adding this to your settings to force it to not bring iRacing to the front. But it may make it worse. 

IRacing-title = dummy


- Jeff Gilliam

**Comment by DaKicker8** [comment]
This command goes in the SRA settings, correct?

**Comment by jfgilliam** [comment]
Yes

- Jeff

**Comment by DaKicker8** [comment]
Testing now. Will upload log afterwards

**Comment by DaKicker8** [comment]
I tried to advance the session while in practice but it would not work
[SIMRacingApps-0.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/6469504/SIMRacingApps-0.log.txt)

**Comment by DaKicker8** [comment]
After changing it back, it started working, with everything registering. So I'm not entirely sure what was wrong
[SIMRacingApps-0.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/6469524/SIMRacingApps-0.log.txt)
