### ISSUE TITLE
NASCAR Next Gen 2022 Brake Bias off by 4% from Black Box

### ISSUE THREAD

**Issue by jfgilliam** [SIMRacingApps/SIMRacingApps#259]
Seems to be an iRacing bug where the telemetry is not returning the same value as shown in the black box. Add code to compensate for it by reading the setup data and comparing it to the current reading and calculate an offset. This should also help cars that the telemetry only returns the delta.

Path to setup on this car is : /iRacing/CarSetup/Chassis/Front/FrontBrakeBias. This value as a % sign at the end of it.

**Comment by Dan2424** [comment]
It's not always off by 4%.  The reading changes depending on the difference between the master cylinder sizes.  The bigger the difference in sizes the bigger the difference between what's on the setup page and what telemetry reads.

**Comment by jfgilliam** [comment]
True. I'm going to fix it so that it matches the blackbox no matter what the telemetry says. I'm testing it now. I will try to release next week, but there are many changes coming for iRacing I need to get into SRA as well. I'm going to read the setup value and the telemetry value each time your car drops onto pit road or the track and save the difference so that I can adjust the telemetry value to match the blackbox. Doing it this way, if iRacing fixes it, the difference will be zero and it will still work.

**Comment by Dan2424** [comment]
Sounds good!  As far as I know, other cars that have adjustable master cylinders are not affected.  And I do believe iRacing is aware of the issue so it's just a matter of time before they will fix it (I assume.)
