### ISSUE TITLE
simracingapps not loading

### ISSUE THREAD

**Issue by bryanw2** [SIMRacingApps/SIMRacingApps#261]
It's stuck on the "Loading... If menu doesn't load, verify the SIMRacingAppsServer is running and a firewall isn't blocking it. Then click the Logo to refresh the page." I've tried disabling my Kaspersky firewall and in Windows Firewall it says its allowed. I've also tried reinstalling Java, different versions of simracingapps, but nothing is working.

Any help would be greatly appreciated.

**Comment by jfgilliam** [comment]
Attach your logs from the documents/simracingapps/logs folder

- Jeff

**Comment by BadBoyClub** [comment]
How do I unsubscribe from this email list successfully?

I’ve opted to unsubscribe multiple times on github but still keep getting these messages?

Thanks

**Comment by jfgilliam** [comment]
> How do I unsubscribe from this email list successfully? I’ve opted to unsubscribe multiple times on github but still keep getting these messages? Thanks

I think you have to unwatch this repository. If that doesn't work, get with Github support. I do not know.

**Comment by bryanw2** [comment]
[SIMRacingApps-1.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/8236677/SIMRacingApps-1.log.txt)
[SIMRacingApps-2.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/8236678/SIMRacingApps-2.log.txt)
[SIMRacingApps-0.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/8236679/SIMRacingApps-0.log.txt)

**Comment by jfgilliam** [comment]
No issues found in the log. With SRA running, open browser with this link

Http://localhost 


- Jeff Gilliam

**Comment by bryanw2** [comment]
Thanks, that worked. Is there any reason why the app wouldnt work?

**Comment by bryanw2** [comment]
Just found why it would work in localhost but not the app itself. My VPN blocked all other network devices even when not connected to the VPN.

**Comment by jfgilliam** [comment]
Ok that helps. I’ve build in ways to work around certain networking issues. Please add this line in the settings and restart SRA.

Electron-hostname = localhost


- Jeff Gilliam
