### ISSUE TITLE
Pìt stop countdown

### ISSUE THREAD

**Issue by rodrigocbb** [SIMRacingApps/SIMRacingApps#262]
Hi there,

I had recentlyformated my ssd and after installiugn SIMRacingApps again everything worked with EXCPETION of the pit stop countdown. Can some one please help me out,

This is how my config lools like:

Sounds-PitCountDown = Y
pit-count-down-device = [Alto-falantes (Realtek High Definition Audio)]
pit-count-down-pattern = C:\\Program Files (x86)\\iRacing\\sound\\spcc\\JJ Spotter Pack v6.70\\n%d.wav
pit-count-down-volume = 100
pit-count-down-play10 = Y
pit-count-down-play0  = Y
pit-count-down-start  = 5
pit-count-down-replay = false

Thanks!

**Comment by jfgilliam** [comment]
It was turned off because IRacing has it’s own now. To turn it back on, add this to your settings.

Pit-count-down-enabled = Y


- Jeff Gilliam

**Comment by rodrigocbb** [comment]
> It was turned off because IRacing has it’s own now. To turn it back on, add this to your settings. Pit-count-down-enabled = Y - Jeff Gilliam
> […](#)
> On Apr 17, 2022, at 4:38 PM, rodrigocbb ***@***.***> wrote: ﻿ Hi there, I had recentlyformated my ssd and after installiugn SIMRacingApps again everything worked with EXCPETION of the pit stop countdown. Can some one please help me out, This is how my config lools like: Sounds-PitCountDown = Y pit-count-down-device = [Alto-falantes (Realtek High Definition Audio)] pit-count-down-pattern = C:\Program Files (x86)\iRacing\sound\spcc\JJ Spotter Pack v6.70\n%d.wav pit-count-down-volume = 100 pit-count-down-play10 = Y pit-count-down-play0 = Y pit-count-down-start = 5 pit-count-down-replay = false Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

**Comment by rodrigocbb** [comment]
Thamk you Jeff! Do you know how to disable iracing´s countdown?:

**Comment by jfgilliam** [comment]
Set the spotter chasteness to low


- Jeff Gilliam
