### ISSUE TITLE
Changing units

### ISSUE THREAD

**Issue by rodrigocbb** [SIMRacingApps/SIMRacingApps#263]
Good morning to you all,

Could any one help me to change SimRcingApps fuel APP unit from metric to US?

Thanks!

**Comment by jfgilliam** [comment]
It responds to the setting in IRacing


- Jeff Gilliam

**Comment by rodrigocbb** [comment]
> It responds to the setting in IRacing - Jeff Gilliam
> […](#)
> On Apr 21, 2022, at 6:52 AM, rodrigocbb ***@***.***> wrote: ﻿ Good morning to you all, Could any one help me to change SimRcingApps fuel APP unit from metric to US? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Ok, Thank you
