### ISSUE TITLE
Enhancement: 2 possible widgets Live/Replay

### ISSUE THREAD

**Issue by thomprl** [SIMRacingApps/SIMRacingApps#264]
When watching/spectating a race would it be possible to have a widget to display a Replay graphic to show that you aren't watching the current live action and rewind the race to watch a accident?  And then possible to have another widget that says Live when watching live action?  I'm not real sure how it would work from the SDK.

**Comment by jfgilliam** [comment]
Probably could be done with one widget. What would be a good name for it?

**Comment by jfgilliam** [comment]
[SIMState.sra.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/9355422/SIMState.sra.zip)

download attachement and remove the .zip extension. Then upload it to SRA at the bottom of the main menu.

**Comment by jfgilliam** [comment]
The attached widget would not detect you were out of the car and live on the replay screen. Had to look at that frames from end of tape to fix that. That is a server change and will be in the next release.

**Comment by jfgilliam** [comment]
released
