### ISSUE TITLE
Can not start pit count down starting at 10

### ISSUE THREAD

**Issue by rodrigocbb** [SIMRacingApps/SIMRacingApps#270]
Hi folks,

I can t have my pit countdown start at 10. I have already change the settings to start countdown = 10, but still starting either at 5 or sometimes no counting at all. Can someone help me with this?

Thanks.

**Comment by jfgilliam** [comment]
You should be able to just change this one variable in the settings.
pit-count-down-start  = 10
If that doesn't work, attach your logs found in Documents/SIMRacingApps/logs.
- Jeff 

    On Tuesday, February 21, 2023 at 04:02:45 PM EST, rodrigocbb ***@***.***> wrote:  
 
 


Hi folks,

I can t have my pit countdown start at 10. I have already change the settings to start countdown = 10, but still starting either at 5 or sometimes no counting at all. Can someone help me with this?

Thanks.

**Comment by rodrigocbb** [comment]
> You should be able to just change this one variable in the settings. pit-count-down-start  = 10 If that doesn't work, attach your logs found in Documents/SIMRacingApps/logs. - Jeff On Tuesday, February 21, 2023 at 04:02:45 PM EST, rodrigocbb ***@***.***> wrote: Hi folks, I can t have my pit countdown start at 10. I have already change the settings to start countdown = 10, but still starting either at 5 or sometimes no counting at all. Can someone help me with this? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by rodrigocbb** [comment]
> > You should be able to just change this one variable in the settings. pit-count-down-start  = 10 If that doesn't work, attach your logs found in Documents/SIMRacingApps/logs. - Jeff On Tuesday, February 21, 2023 at 04:02:45 PM EST, rodrigocbb _**@**_._**> wrote: Hi folks, I can t have my pit countdown start at 10. I have already change the settings to start countdown = 10, but still starting either at 5 or sometimes no counting at all. Can someone help me with this? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>

Thanks Jeffrey ! It seems to be working now. I will post my settings here if that happens again.
