### ISSUE TITLE
Help with Windows Defender

### ISSUE THREAD

**Issue by rodrigocbb** [SIMRacingApps/SIMRacingApps#271]
Hi,

Need help with configurantion to pass thru Windows Defender. Was working fine than suddenly stop working.

Thanks,

**Comment by jfgilliam** [comment]
What is the issue? Normally you have to make it run anyway. But, once you do that once, it remembers it until you download it again.

**Comment by rodrigocbb** [comment]
> What is the issue? Normally you have to make it run anyway. But, once you do that once, it remembers it until you download it again.

Sorry, forgot to mentioned. It does not load on my iPad.

**Comment by jfgilliam** [comment]
Ok. You probably don't have a Defender issue, you have a firewall issue. Go to this link for help to resolve it.

https://github.com/SIMRacingApps/SIMRacingApps/wiki/How-to-fix-Firewall-issues

**Comment by rodrigocbb** [comment]
> Ok. You probably don't have a Defender issue, you have a firewall issue. Go to this link for help to resolve it.
> 
> https://github.com/SIMRacingApps/SIMRacingApps/wiki/How-to-fix-Firewall-issues

You got it. Problem fixed. Thank you.

**Comment by rodrigocbb** [comment]
Problem resolved.
