### ISSUE TITLE
Mangy-Cours track map

### ISSUE THREAD

**Issue by Coreyhasnolife** [SIMRacingApps/SIMRacingApps#274]
it seems the mangy cours track map is a little off compared to where the cars actually are on the track, i think if the finish line and the trigger for new lap is moved closer to the final corner it might fix the issue

**Comment by jfgilliam** [comment]
This fix is now available in Version: 1.21_Build_2024.01.21

**Comment by jfgilliam** [comment]
I could clearly see the correct finish line with google maps. The iRacing track map has it wrong.
