### ISSUE TITLE
Sound Plugin Announce Pit Road Speed as entering the pits.

### ISSUE THREAD

**Issue by jfgilliam** [SIMRacingApps/SIMRacingApps#49]
Suggested by Ty Hester.

**Comment by BadBoyClub** [comment]
+ 1, this would be a great addition. If possible also announce again once you leave the pit box

**Comment by jfgilliam** [comment]
Since I don't plan to support text to speech right now, I added this to the Voice Attack Profile. Until version 1.2 is released, you can get it from the Files section in the SIMRacingAppsBETA group on facebook. Just ask to join if you haven't already.
@BadBoyClub
