### ISSUE TITLE
Camera Change Widgit not functional

### ISSUE THREAD

**Issue by MirrorImageQS** [SIMRacingApps/SIMRacingApps#75]
The Camera Change widgit does not change to the selected car. Tested in both DX9 and DX11 and both while running the program as administrator and while not.

**Comment by jfgilliam** [comment]
Which widget(s)/app(s) did you try?

**Comment by MirrorImageQS** [comment]
I tried both the one from the Broadcaster,Spotter-CAMERA app and the individual CarSelector-CAMERA widget. Each time, the console did register the command to change car, but the sim did not respond to it.

I also tried moving the logging up to FINEST, but there were no additional messages printed at the time.

**Comment by jfgilliam** [comment]
Thanks I will test when I get home. in the meantime can you tell me if you can change the camera manually in the session that you're in

- Jeff

**Comment by MirrorImageQS** [comment]
If by manually you mean the iRacing controls, yes. I can cycle through cars and use the user drop down list in the sim.

**Comment by jfgilliam** [comment]
Thanks for the video, that helped a lot. I have been able to confirm what you say. All my testing has been done as a spectator in official sessions where the car number and the car index is the same. I got into a practice session and I saw the problem. The camera code wants the car number, not the car index (which is what I was using). I tested that it can work by changing the code to the car number, but I know there's a trick to get it to work with numbers that have a leading zero. The iRacing API wants the car number as an integer. Tomorrow I will search the forum for the math to distinguish between 1, 01, 001.

Thanks again for your help.

**Comment by jfgilliam** [comment]
I have fixed this issue and it will be available in the 1.2 release in December 2016. You can get the BETA version of 1.2 by going to [releases](https://github.com/SIMRacingApps/SIMRacingApps/releases) and downloading the version with a date greater or equal to 2016.11.14.
