### ISSUE TITLE
Blue flag in multi class identifies drivers in same class only

### ISSUE THREAD

**Issue by samkatakouzinosracing** [SIMRacingApps/SIMRacingApps#78]
When a driver in another class is approaching me on track, some other person and time gets announced. 
Seems blue flags are triggered correctly but the wrong driver named if not same class as me.

**Comment by jfgilliam** [comment]
Thanks for pointint that out. I created 2 new commands "Behind Relative" and "Ahead Relative". Then I changed the blue flag to call the "Behind Relative". I have attached the new profile here. I have not had time to test it. Will you let me know if it is working properly and I'll include these changes in the next public release.

[SIMRacingApps-VoiceAttack-Profile.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/649019/SIMRacingApps-VoiceAttack-Profile.zip)

**Comment by samkatakouzinosracing** [comment]
Unable to test at the moment as Voice Attack keeps crashing.
Kinda around since new build.
Voice Attack v1.6.1.7
SIMRacingAppsServer 1.2 Build BETA 2016.12.05

**Comment by jfgilliam** [comment]
OK, let me know if you think it is crashing because of my profile. I'm running the same version, I think. All mine says is 1.6.1, but a version check says it's the latest. One thing I don't know how to work around, is if the SRA server is not running, VA will be unresponsive. It is trying to reach the server and it can't, so it hangs. I think that's something VA needs to address so it doesn't hang when a URL isn't responding.

**Comment by samkatakouzinosracing** [comment]
Ok. VA not crashing because of your profile but because I entered an invalid custom port number. 
VA doesn't have a graceful method to continue when calling an invalid host/port. It just hangs and dies. 

PS sorry for the delay.

**Comment by jfgilliam** [comment]
Same thing happens to me when I shutdown the server before I close VA. Don't know a graceful way around that. If there's a fix, VA would probably have to fix it.

**Comment by samkatakouzinosracing** [comment]
I created an issue over at http://voiceattack.com/smf/index.php?topic=907.0 
"VA hangs when accessing invalid URI"

**Comment by samkatakouzinosracing** [comment]
VoiceAttack beta v1.6.1.34; Fixed issue with setting text variable by URI hanging the entire user interface.
http://voiceattack.com/smf/index.php?topic=963.0
