### ISSUE TITLE
Tire Measurements Don't Change on all Dallara tires

### ISSUE THREAD

**Issue by TristanAnderson2** [SIMRacingApps/SIMRacingApps#86]
When I'm running laps in iRacing i click the "fuel and 4 tires" button and when i do go to pit.  my crew changes the tires and fill the fuel but the app only tells me my right rear tire was changed and still says i ran *amount of laps* on the other three tires.  Please help me fix this

**Comment by jfgilliam** [comment]
Sorry to hear this is happening to you. I have heard of one other person that this is occurring on, yet he said it was intermittent. Does it happen to you every time? ------------------------------------------------------
 Jeff

**Comment by TristanAnderson2** [comment]
it seems to work fine the first time i pit but everytime after this it happens, sometimes it says no tires were changed and it scares me sometimes in important races haha

**Comment by jfgilliam** [comment]
Do you find it is worse for certain cars? If so, which ones? ------------------------------------------------------
 Jeff

**Comment by TristanAnderson2** [comment]
Currently ive had it happen in the DW 12's and the Indycar Dallara circa 2011.  Those are the only cars ive been driving lately because thats what my league runs

**Comment by jfgilliam** [comment]
Thanks, I'm an oval guy, so I don't run these. I will get into a practice session and see if I can duplicate your problem. ------------------------------------------------------
 Jeff

**Comment by TristanAnderson2** [comment]
okay, that would be awesome.  Im also a oval guy.  our league runs Indycars at oval tracks.  Very fun
And i also had another question.  Say me and a friend wanted to join a race and he wanted to spot/be my crew chief.  We have been testing things and we havent found anyway from him to be able to use the CrewChief Large app and control my pit stops with it and select which tires will be changed and how much fuel to add.

**Comment by jfgilliam** [comment]
Is that a feature he can do without the app? I don't think he can see your fuel level. 

- Jeff

**Comment by TristanAnderson2** [comment]
im not sure, i was hoping there was a way to do it with the app but its
okay if there isnt
And i just ran a race in the trucks and the app worked perfectly so i think
its just in those 2 cars as far as i know.  Could it be have something to
do with the fact the whole car gets jacked up a once and all tires are
remove at the same time?  just an idea.  Hopefully you find a fix for this
but other then that, loving the app so far!

**Comment by jfgilliam** [comment]
If you can do it manually, then it should work through the App. If not, I'm going to have to post a bug to iRacing. I'm using their API to change the pit settings. I think you can have multiple spotters, but only one of them can be a crew chief. I don't know how one becomes a crew chief. ------------------------------------------------------
 Jeff

**Comment by TristanAnderson2** [comment]
I'll try to figure it out because i know you can do it manually but it you
find a fix for that tire problem I'm having on the Indycars please let me
know, that would be great thank you!

**Comment by jfgilliam** [comment]
I have found the problem for the Indy cars. But, I want to test it on several other cars before I release it. Thanks for reporting it. It was a timing issue because iRacing was sending the tire change information faster on these cars than the others I run. I had a delay in the tire reading so I could detect if you overshot your pit. But that logic isn't needed anymore since a few versions back, iRacing fixed it in their code. So, I took out the delay.
When's your next league race? ------------------------------------------------------
 Jeff

**Comment by TristanAnderson2** [comment]
Awesome to hear!  thank you for finding the issue so quickly, i am very
impressed!  You truly have made something awesome here.

**Comment by jfgilliam** [comment]
OK, I just posted a new BETA release with this fix. ------------------------------------------------------
 Jeff

**Comment by TristanAnderson2** [comment]
Awesome Great work! Thank you so much.
