### ISSUE TITLE
RaceAdministrator Application: Clear All Penalties for All Drivers

### ISSUE THREAD

**Issue by MirrorImageQS** [SIMRacingApps/SIMRacingApps#88]
Requesting the addition of a "Clear Penalties for All Drivers" function.

For the purpose of this, it would be sufficient to loop through all car numbers in the session and individually send a !clear command, regardless of whether they actually have a penalty or not.

To avoid confusion, the existing "Clear All Penalties" buttons should also be renamed to "Clear Penalties" to prevent confusing the scope of its function.

This would be useful for leagues who implement alternative race procedures not inherently driven by iRacing. One such example is leagues who implement Class Splitting by giving EOL commands to all cars of a certain class. It is quite common for that entire field to be black flagged for passing under yellow if there is a straggler of the faster class trying to catch up the field.

**Comment by jfgilliam** [comment]
Moved your comments to #13, which is a duplicate request. Please add any more comments to #13
