### ISSUE TITLE
StandingsTopX widgets

### ISSUE THREAD

**Issue by MirrorImageQS** [SIMRacingApps/SIMRacingApps#90]
Related to #89, with larger field sizes, there is not a Standings Widget of the appropriate size to display the entire field for large fields.

Requesting the creation of a StandingsTop60 widget. Also requesting that this new widget replace the existing Standings widgets in the default apps that utilize it (Spectator, Crew Chief, etc.). To accommodate its size, the widget could automatically wrap itself with a scroll bar (or some other sort of scrolling).

**Comment by jfgilliam** [comment]
Scrolling is not possible in SRA. Therefore, I created a Top60 Widget, but I did not update the other apps because I think it would be too small.

**Comment by jfgilliam** [comment]
Created StandingsTop60, Spectator60, Spotter60
