### ISSUE TITLE
Voice Attack: Announce times as Minutes and Seconds when over 59s

### ISSUE THREAD

**Issue by samkatakouzinosracing** [SIMRacingApps/SIMRacingApps#92]
I would like announced times to be expressed as minutes and seconds when time value is over 59 seconds. 

I would prefer to hear 'Leader is 2 minute, 15 seconds ahead' rather than 'Leader is 135 seconds ahead'.

**Comment by jfgilliam** [comment]
I changed Ahead/Behind to be for all classes. Got rid of Ahead/Behind Relative and replaced them with Ahead/Behind Class. These now all say the times in minutes (if greater than zero) and Seconds. Let me how it goes and I'll put it in the next release.

Here is the profile: [SIMRacingApps-VoiceAttack-Profile.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/832135/SIMRacingApps-VoiceAttack-Profile.zip)

**Comment by jfgilliam** [comment]
Added some more chat commands (Thanks, You're Welcome, Pitting In, Pitting Out)

[SIMRacingApps-VoiceAttack-Profile.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/836024/SIMRacingApps-VoiceAttack-Profile.zip)

**Comment by jfgilliam** [comment]
Fixed a rounding error where anything greater than 30 seconds on the minute, would round the minutes up.

[SIMRacingApps-VoiceAttack-Profile.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/837153/SIMRacingApps-VoiceAttack-Profile.zip)

**Comment by samkatakouzinosracing** [comment]
Entered a session and the quickest lap time of 1:16.725 was spoken as "minus {short blank space) 16.725 seconds ahead".
The minutes part was missing?

**Comment by jfgilliam** [comment]
OK, I tried a different approach on the rounding. Try this one out.

[SIMRacingApps-VoiceAttack-Profile.zip](https://github.com/SIMRacingApps/SIMRacingApps/files/841820/SIMRacingApps-VoiceAttack-Profile.zip)
