### ISSUE TITLE
Teamspeak 3.1.3 Issue

### ISSUE THREAD

**Issue by BadBoyClub** [SIMRacingApps/SIMRacingApps#96]
Teamspeak app no longer works with today's Teamspeak update 3.13. I get the following error:

`20170324144302.759: WARNING: TeamSpeak: _getClientList(): returned error 1796, currently not possible: com.SIMRacingApps.TeamSpeak._getClientList(TeamSpeak.java:320)[TeamSpeak.Listener]`

**Comment by jfgilliam** [comment]
I could not find a work around for this issue and I didn't get a response from TeamSpeak on how to disable it. I have added the ability put you key in the settings.txt file as follows, but you have to be on release 1.2 - 2017.03.27 or later.

teamspeak-apikey = your key

You can find your key in TeamSpeak -> Options -> Addons -> Plugins -> ClientQuery -> Settings
and either update or add an entry to the settings.txt file.

**Comment by BadBoyClub** [comment]
Thnan ks Jeff, I assume that version hasn't been released yet? I only see "Version_1.2_Build_BETA-2017.03.18" on https://github.com/SIMRacingApps/SIMRacingApps/releases

**Comment by BadBoyClub** [comment]
10-4, thanks

**Comment by jfgilliam** [comment]
version 1.2_Build_BETA-2017.03.30 posted at https://github.com/SIMRacingApps/SIMRacingApps/releases
