### ISSUE TITLE
Lap# and Scoring Froze

### ISSUE THREAD

**Issue by runninwideopen** [SIMRacingApps/SIMRacingApps#97]
With 41 laps to go, the lap count froze on the StandingsBanner, CrewChief and Dash_barGauges-DigitalOverlay widgets.   As well, the scoring information in the StandingsBanner widget should every driver but the leader 30+ laps down.

**Comment by jfgilliam** [comment]
Please attach your logs found in Documents/SIMRacingApps/logs

- Jeff

**Comment by runninwideopen** [comment]
[SIMRacingApps-0.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/870096/SIMRacingApps-0.log.txt)
[SIMRacingApps-1.log.txt](https://github.com/SIMRacingApps/SIMRacingApps/files/870095/SIMRacingApps-1.log.txt)

I think -0 is the one from that session.
If you want to see what the scoring was showing, you can see: https://youtu.be/Ms6LM01G34E    just skip to the second half.

**Comment by jfgilliam** [comment]
Well I don't see anything abnormal in the logs. How often had this happened? I see your stream is only showing the banner, what are the others running on?

- Jeff

**Comment by runninwideopen** [comment]
It used to happen often when I first download it about 4 months ago.  I downloaded a beta release for the first time a month or two ago and everything was working pretty well on that release.   Since the last update, I've had this problem a couple times.  

I'm also using the Dash-BarGauges-Digital Overlay on a 4th monitor, same computer, as my dashboard and there are other apps/widgets used in different OBS scenes.  I use the standings43, standings20, broadcast overlay, flag, etc.   Also, on a 5th monitor, driven by a different computer, I use the Crew Chief app while driving or the Broadcaster camera selecting app while broadcasting.

**Comment by jfgilliam** [comment]
Wow, you are really loading it down. Let's try a couple of things. First, let's try getting you in the 64 bit version of Java. See here https://github.com/SIMRacingApps/SIMRacingApps/wiki/Java-64-Bit-Installation

If that doesn't help we might need to adjust the memory Java uses 

- Jeff

**Comment by runninwideopen** [comment]
Hey, it's good stuff!   :)

Alright, 64bit java installed.  I have a race tonight.  I'll let you know if anything goes awry.  Thanks!

**Comment by runninwideopen** [comment]
So the laps to go count did seem to freeze for about 15 laps last night.  But then it started working after a caution/pit cycle.  

On the bright side, I successfully updated my CSS styles and love it.  Thx for making that available.

**Comment by jfgilliam** [comment]
OK, let's try giving SRA a little more memory. I've outlined how to do this at https://github.com/SIMRacingApps/SIMRacingApps/wiki/How-to-Define-Java-Parameters. If you have enough extra memory, let's double it.

-Xms512m
-Xmx1024m

If not enough memory, try

-Xms512m
-Xmx768m

**Comment by runninwideopen** [comment]
I'm pretty sure I did that right - seems pretty straightforward.  I did double it.  Last night I never noticed any scoring problems, but the lap tracker and resulting lap time was often off.

Forgot to mention that before - that's not new.    It's always faster.  Sometimes .1, sometimes 1.0.   I thought I was flying!   

-- Tom Ohmit --
-----mobile-----

**Comment by jfgilliam** [comment]
That's good to hear. Making progress.
Are you referring to the TimingDelta widget? ------------------------------------------------------
 Jeff

**Comment by jfgilliam** [comment]
Also, to verify the ini file worked, open the task manager, right click on the header and select command line so you can see it. Then scroll down to the "java.exe" process. Even though you will see the memory with the defaults and then your settings, it uses the last one it finds.

**Comment by runninwideopen** [comment]
Sorry, I've never done that before.   Where's the header?   I tried right-clicking around but wasn't able to find any command line.

-- Tom Ohmit --
-----mobile-----

**Comment by jfgilliam** [comment]
It's the column titles



- Jeff Gilliam


-------- Original message --------

**Comment by runninwideopen** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/26665034/24591163/6afc4b0a-17c0-11e7-9864-7e1d854331e5.png)

I can't seem to find what I'm doing wrong.  I don't think it actually is loading.   Here's a screenshot with my .ini file, location and the task manager.    Can you see what I've messed up?


Yes, I was referring TimingDelta widget.

**Comment by jfgilliam** [comment]
No it's not using it. It may be because of a hidden extension. In the file manager, under view, turn on File Name Extensions. I bet you'll need to rename it after you can see it.
------------------------------------------------------
 Jeff

**Comment by jfgilliam** [comment]
On the TimingDelta widget, I looked at my logic again and it is pretty straight forward. iRacing gives me the Split Delta time in the telemetry. It's the same value you see when you turn on the split times (TAB). I use the Best Session Lap by default. So, if you keep hitting tab until iRacing is showing the Best Session Lap, then my numbers will match theirs. So, to get to the projected time, I just add that number to you Best Session Lap time. So, in a nutshell, iRacing will have to get their calculation better :)

**Comment by runninwideopen** [comment]
Most of the time it works great, but it is inconsistent.    I was just in a practice session and it was telling me I was headed for a 31.5 lap time - and when crossing the start/finish line it froze and showed 31.5 as my lap time.    But my actual iRacing lap time was a 27.8.   

It does that throughout a race too - it'll get off for a few minutes and then all of a sudden it's off again.  


Regarding the .ini file - you were right it had a phantom .txt extension which I have removed.   But it still doesn't appear to be loading the new memory settings.  Any other suggestions to try?

-- Tom Ohmit --
-----mobile-----

**Comment by jfgilliam** [comment]
attach you .ini file. ------------------------------------------------------
 Jeff

**Comment by runninwideopen** [comment]
I downloaded the new 1.2 release and renamed my ini file and now it is taking the new memory params.  I'll let you know if I have any issues tonight.   Thanks for all your help!

**Comment by runninwideopen** [comment]
Oh, it looks like my last email response didn't got through.   

In my Texas race, the timing and scoring issues both pollled up again.  For only a few laps, and then things were correct again.

**Comment by jfgilliam** [comment]
Well at least it is moving in the right direction. 

- Jeff

**Comment by jfgilliam** [comment]
If this problem has fixed itself, then please close this issue.

**Comment by runninwideopen** [comment]
No, this still happens.   I just moved and haven't gotten setup yet.  It will be about a month before I can keep working on it.

-- Tom Ohmit --
-----mobile-----
